# Generated by Django 3.2.25 on 2024-05-17 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professions',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='zodiacsign',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
